<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('User profile'); ?></h1>
    </div>
    <p class="lead">

    </p>
    <div class="row">
        <div class="col-sm-8">
            <div>
                <h2><?php echo $this->translate('Personal information'); ?></h2>
                <p>
                    <?php echo $this->translate('Username'); ?>: <?php echo $this->escapeHtml($user->getUsername()); ?>
                </p>
                <p>
                    <?php echo $this->translate('Timezone'); ?>: <?php $timezone = $user->getTimebelt();
                    if ($timezone instanceof \DateTimeZone) {
                    echo $this->escapeHtml($timezone->getName()); } ?>
                </p>
                <p>
                    <?php echo $this->translate('Email'); ?>: <?php echo $this->escapeHtml($user->getEmail()); ?>
                </p>
                <p>
                    <?php echo $this->translate('Role'); ?>: <?php echo $this->escapeHtml($user->getRole()); ?>
                </p>
                <p>
                    <?php echo $this->translate('Language'); ?>: <?php echo $this->escapeHtml($user->getLocale()); ?>
                </p>
                <p>
                    <?php echo $this->translate('Created'); ?>: <?php if ($user->getCreated() instanceof \DateTimeInterface) {
                    echo $this->formatDateI18n($user->getCreated());
                } ?>
                </p>
                <p>
                <a href="<?php echo $this->url('editPassword', array('action' => 'editPassword')); ?>"><?php echo $this->translate('Change password'); ?></a>
            </p>
            <p>
                <a href="<?php echo $this->url('editEmail', array('action' => 'editEmail')); ?>"><?php echo $this->translate('Change email'); ?></a>
            </p>
            <p>
                <a href="<?php echo $this->url('editUser', array('action' => 'editUser', 'id' => $user->getId())); ?>"><?php echo $this->translate('Edit user'); ?></a>
            </p>
            <p>
                <a href="<?php echo $this->url('deleteUser', array('action' => 'deleteUser', 'id' => $user->getId())); ?>"><?php echo $this->translate('Delete user'); ?></a>
            </p>
            </div>
        </div>
    </div>
</div>