<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="page-header">
            <h1><?php echo $this->translate('Users') ?></h1>
        </div>
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button">Toggle nav</button>
            </p>
            <?php $countColumns = 3;
            $count = $this->users->getCurrentItemCount();
            $iterator = $this->users->getIterator();
            if ($count):
                for ($i = 0; $i < $count; $i = $i + $countColumns ): ?>
                    <div class="row">
                        <?php for ($j = 0; $j < $countColumns; $j++):
                            if ($iterator->valid()): ?>
                                <div class="col-xs-12 col-md-4">
                                    <div class="div-1">
                                        <?php $user = $iterator->current();
                                        $iterator->next(); ?>
                                        <h1><a href="<?php echo $this->url('detailUser',
                                            array('action' => 'detailUser', 'id' => $user->getId())); ?>">
                                            <?php echo $this->escapeHtml($user->getUsername()); ?></a>
                                        </h1>
                                        <p>
                                            <?php $createdDate = '00.00.0000';
                                                if ($user->getCreated() instanceof \DateTimeInterface) {
                                                    $createdDate = $this->formatDateI18n($user->getCreated());
                                                    echo $this->escapeHtml($user->getUsername())
                                                    . ' ' . $this->translate('was registered at')
                                                    . ' ' . $createdDate
                                                    . ' ' . $this->translate('and has')
                                                    . ' ' . $this->escapeHtml($user->getRole())
                                                    . ' ' . $this->translate('role');
                                                }
                                            ?>
                                        </p>
                                    </div>
                                    <p><a role="button" href="<?php echo $this->url('listPostsByUser',
                                        array('action' => 'listPostsByUser', 'id' => $user->getId())); ?>" class="btn btn-default"><?php echo $this->translate('User\'s content') ?></a>
                                    </p>
                                </div>
                            <?php endif;
                        endfor; ?>
                    </div>
                <?php endfor;
            endif; ?>
        </div>
        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class="list-group">
                <a class="list-group-item" href="<?php echo $this->url('listCategories',
                    array('action' => 'listCategories')); ?>"><?php echo $this->translate('Categories') ?></a>
                <a class="list-group-item" href="<?php echo $this->url('listTags',
                    array('action' => 'listTags')); ?>"><?php echo $this->translate('Tags') ?></a>
            </div>
        </div>
    </div>
    <?php echo $this->paginationControl($this->users,
        'Sliding',
        'partial/paginator.phtml',
        array('route' => $this->route)); ?>
</div>