

<?php if ($this->error) : ?>
<p class="error">
    There were one or more issues with your submission. Please correct them as
    indicated below.
</p>
<p>
    <?php echo $this->escapeHtml($this->translate($this->error)); ?>
</p>
<?php endif; ?>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('loginUser', array(), true));
$form->prepare();

echo $this->form()->openTag($form); ?>

<h2 class="form-signin-heading"><?php echo $this->escapeHtml($this->translate('Please log in')); ?></h2>

<?php
echo $this->formLabel($form->get('email'));
echo $this->formElement($form->get('email'));
echo $this->formElementErrors($form->get('email'));     //TODO ошибки в модальном окне?

echo $this->formLabel($form->get('password'));
echo $this->formElement($form->get('password'));
echo $this->formElementErrors($form->get('password'));

echo $this->formElement($form->get('redirect'));
echo $this->formElement($form->get('login_csrf'));

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>

            </div>
        </div>
    </div>
</div>
