<?php if ($this->error): ?>
    <div class="container" id="error-login">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
            <?php
                echo $this->translate("There were one or more issues. Please correct them as indicated below.");
            ?>
            <strong>
                <?php
                    if (is_string($this->error)) {
                        ?><div id="error-message"><?php echo $this->escapeHtml($this->translate($this->error)) . "!"; ?></div><?php
                    }
                    echo $this->formElementErrors($form->get('email'), ['id' => 'error-email']);
                    echo $this->formElementErrors($form->get('password'), ['id' => 'error-password']);
                ?>
            </strong>
        </div>
    </div>
<?php endif; ?>
<div class="container">
    <?php
        $flash = $this->flashMessenger();
        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
    ?>
</div>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner dialog">
                <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('loginUser', array(), true));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                ?>
                <h2 class="form-signin-heading">
                    <?php echo $this->escapeHtml($this->translate('Please log in')); ?>
                </h2>
                <div class="form-group <?php echo empty($form->get('email')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php
                        echo $this->formLabel($form->get('email'));
                        echo $this->formElement($form->get('email'));
                    ?>
                </div>
                <div class="form-group <?php echo empty($form->get('password')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php
                        echo $this->formLabel($form->get('password'));
                        echo $this->formElement($form->get('password'));
                    ?>
                </div>
                <?php
                    echo $this->formElement($form->get('redirect'));
                    echo $this->formElement($form->get('login_csrf'));

                    echo $this->formElement($form->get('submit'));

                    echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>