<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner dialog">
                <h2 class="form-signin-heading">
                    <?php echo $this->translate('Are you sure that you want to delete'); ?>?
                </h2>
                <p>
                    <?php echo $this->translate('Article'); ?>
                    "<?php echo $this->escapeHtml($this->post->getTitle()); ?>"
                    <?php echo $this->translate('by author'); ?>
                    "<?php echo $this->escapeHtml($this->post->getAuthor()->getUsername()); ?>"
                </p>
                <form action="<?php echo $this->url('deletePost', array(), true) ?>" method="post">
                    <input type="submit" class='btn btn-default' name="delete_confirmation" value="yes">
                    <input type="submit" class='btn btn-default' name="delete_confirmation" value="no">
                </form>
            </div>
        </div>
    </div>
</div>