<div class="container">
    <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
    </div>

    <div class="row">
        <div class="col-sm-8 blog-main">
            <div class="blog-post">
                <h2 class="blog-post-title"><?php echo $this->escapeHtml($category->getTitle()); ?></h2>
                <p class="blog-post-meta">
                    Category ID: <?php echo $this->escapeHtml($category->getId()); ?>
                </p>
                <p class="blog-post-meta">
                    Category decription: <?php echo $this->escapeHtml($category->getDescription()); ?>
                </p>
            </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
                <h4>About</h4>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            </div>
            <div class="sidebar-module">
                <?php echo $this->partial('partial/listArchivePanel.phtml'); ?>
            </div>
            <div class="sidebar-module">
                <h4>Elsewhere</h4>
                <ol class="list-unstyled">
                  <li><a href="#">GitHub</a></li>
                  <li><a href="#">Twitter</a></li>
                  <li><a href="#">Facebook</a></li>
                </ol>
            </div>
            <div class="sidebar-module">
                <?php echo $this->partial('partial/contentManagerPanel.phtml'); ?>
            </div>
        </div><!-- /.blog-sidebar -->
    </div>
</div>