<div class="container">
    <div class="page-header">
        <h1>The Bootstrap Blog</h1>
    </div>
    <p class="lead"><?php if ($post->getAuthor() instanceof \MxmUser\Model\UserInterface) {
            ?><a href="<?php echo $this->url('listPostsByUser',
            array('action' => 'listPostsByUser', 'id' => $post->getAuthor()->getId(), 'page' => '1')); ?>">
            <?php echo $this->escapeHtml($post->getAuthor()->getUserName()); ?></a>
        <?php } ?>
        <?php if ($post->getPublished() instanceof \DateTimeInterface) {
            echo $this->formatDateI18n($post->getPublished());
        } ?>
    </p>
    <div class="row">
        <div class="col-sm-8">
            <div>
                <h2><?php echo $this->escapeHtml($post->getTitle()); ?></h2>

                <p>
                    <?php echo $this->translate('Category'); ?>: <?php if ($post->getCategory() instanceof \MxmBlog\Model\CategoryInterface) {
                        echo $this->escapeHtml($post->getCategory()->getTitle());
                    } ?>
                </p>
                <p>
                    <?php echo $this->htmlPurifier($post->getText()); ?>
                </p>
                <hr>
                <p>
                    <?php echo $this->translate('Tags'); ?>: <?php if ($post->getTags() instanceof \Zend\Tag\ItemList) { ?>
                    <?php $tags = $this->post->getTags();
                    foreach ($tags as $tag): ?>
                        <?php echo $this->escapeHtml($tag->getTitle());?>
                    <?php endforeach; } ?>
                </p>
            </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
        <?php echo $this->partial('partial/blogSidebar.phtml'); ?>
    </div>
</div>