<div class="container">
    <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
    </div>
    <div class="row">
        <div class="col-sm-8 blog-main">
            <div class="blog-post">
                <h2 class="blog-post-title"><?php echo $this->escapeHtml($tag->getTitle()); ?></h2>
                <p class="blog-post-meta">
                    Tag ID: <?php echo $this->escapeHtml($tag->getId()); ?>
                </p>
                <p class="blog-post-meta">
                    Tag weight: <?php echo $this->escapeHtml($tag->getWeight()); ?>
                </p>
            </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
        <?php echo $this->partial('partial/blogSidebar.phtml'); ?>
    </div>
</div>