<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('Tag'); ?></h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div>
                <h2><?php echo $this->escapeHtml($tag->getTitle()); ?></h2>
                <p>
                    Tag weight: <?php echo $this->escapeHtml($tag->getWeight()); ?>
                </p>
            </div>
        </div>
    </div>
</div>