<!-- FileName: /module/Blog/view/blog/list/detail.phtml -->

<div class="blog-header">
    <h1 class="blog-title">The Bootstrap Blog</h1>
    <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
</div>

<div class="row">
    <div class="col-sm-8 blog-main">
        <div class="blog-post">
            <h2 class="blog-post-title"><?php echo $this->escapeHtml($post->getTitle()); ?></h2>
            <p class="blog-post-meta">
                ID: <?php echo $this->escapeHtml($post->getId()); ?>
            </p>
            <p class="blog-post-meta">
                Category: <?php if ($post->getCategory() instanceof \MxmBlog\Model\CategoryInterface) {
                    echo $this->escapeHtml($post->getCategory()->getTitle());
                } ?>
            </p>
            <p class="blog-post-meta">
                isPiblished: <?php echo $this->escapeHtml($post->getIsPublished()); ?>
            </p>
            <p class="blog-post-meta">
                Version: <?php echo $this->escapeHtml($post->getVersion()); ?>
            </p>
            <p class="blog-post-meta">
                Created: <?php if ($post->getCreated() instanceof \DateTimeInterface) {
                    echo $this->formatDateI18n($post->getCreated());
                } ?>
            </p>
            <p class="blog-post-meta">
                Updated: <?php if ($post->getUpdated() instanceof \DateTimeInterface) {
                    echo $this->formatDateI18n($post->getUpdated());
                } ?>
            </p>
            <p class="blog-post-meta">
                Published: <?php if ($post->getPublished() instanceof \DateTimeInterface) {
                    echo $this->formatDateI18n($post->getPublished());
                } ?>
            </p>
            <p class="blog-post-meta">
                Author: <?php if ($post->getAuthor() instanceof \MxmUser\Model\UserInterface) {
				?><a href="<?php echo $this->url('listPostsByUser',
                            array('action' => 'listPostsByUser', 'id' => $post->getAuthor()->getId(), 'page' => '1')); ?>">
                            <?php echo $this->escapeHtml($post->getAuthor()->getUserName()); ?></a>
            <?php } ?>
            </p>

            <p class="blog-post-meta">
                Tags: <?php if ($post->getTags() instanceof \Zend\Tag\ItemList) { ?>
				<?php $tags = $this->post->getTags();
                $tags->spreadWeightValues([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
                foreach ($tags as $tag): ?>
                    <?php echo $this->escapeHtml($tag->getTitle());?>
                <?php echo $this->escapeHtml($tag->getWeight());?>
                (<?php echo $this->escapeHtml($tag->getParam('weightValue'));?>)
                <?php endforeach; } 	?>
            </p>
            <p>
                <?php echo $this->htmlPurifier($post->getText()); ?>
            </p>
        </div><!-- /.blog-post -->
    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        </div>
        <div class="sidebar-module">
            <?php echo $this->partial('partial/listArchivePanel.phtml'); ?>
        </div>
        <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
        </div>
        <div class="sidebar-module">
            <?php echo $this->partial('partial/contentManagerPanel.phtml'); ?>
        </div>
    </div><!-- /.blog-sidebar -->
</div>