<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('Tag'); ?></h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div>
                <h2><?php echo $this->escapeHtml($tag->getTitle()); ?></h2>
                <p>
                    Tag weight: <?php echo $this->escapeHtml($tag->getWeight()); ?>
                </p>
            </div>
            <?php if ($this->isGranted('edit.tag', $tag)): ?>
                <a role="button" class="btn btn-default" href="<?php echo $this->url('editTag', ['action' => 'editTag', 'id' => $tag->getId()]); ?>"><?php echo $this->translate('Edit') ?></a>
            <?php endif; ?>
            <?php if ($this->isGranted('delete.tag', $tag)): ?>
                <a role="button" class="btn btn-default" href="<?php echo $this->url('deleteTag', ['action' => 'deleteTag', 'id' => $tag->getId()]); ?>"><?php echo $this->translate('Delete') ?></a>
            <?php endif; ?>
        </div>
    </div>
</div>