<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('Category decription'); ?></h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div>
                <h2><?php echo $this->escapeHtml($category->getTitle()); ?></h2>
                <p>
                    <?php echo $this->escapeHtml($category->getDescription()); ?>
                </p>
            </div>
        </div>
    </div>
</div>