<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button"><?php echo $this->translate('Toggle nav') ?></button>
            </p>
            <div class="jumbotron">
                <h1>Hello, world!</h1>
                <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
            </div>
            <div class="row">
                <?php if (count($this->posts)): ?>
                    <?php foreach ($this->posts as $post): ?>
                        <div class="col-xs-6 col-lg-4">
                            <div class="div-1">
                            <h1><a href="<?php echo $this->url('detailPost',
                                array('action' => 'detailPost', 'id' => $post->getId())); ?>">
                                <?php echo $this->escapeHtml($post->getTitle()); ?></a></h1>

                            <p>
                                <?php echo $this->htmlPurifier($post->getSummary()); ?>
                            </p>

                            </div>
    <!--                        <p><a role="button" href="#" class="btn btn-default">View details »</a></p>-->
                        </div><!--/.col-xs-6.col-lg-4-->
                    <?php endforeach; ?>
                <?php endif; ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class="list-group">
                <a class="list-group-item" href="<?php echo $this->url('listPosts',
                    array('action' => 'listPosts')); ?>">Articles</a>
                <a class="list-group-item" href="<?php echo $this->url('listCategories',
                    array('action' => 'listCategories')); ?>">Categories</a>
                <a class="list-group-item" href="#">Archives</a>
                <a class="list-group-item" href="<?php echo $this->url('listTags',
                    array('action' => 'listTags')); ?>">Tags</a>
            </div>
            <?php echo $this->partial('partial/contentManagerPanel.phtml'); ?>
        </div><!--/.sidebar-offcanvas-->
    </div><!--/row-->

    <?php echo $this->paginationControl($this->posts,
            'Sliding',
            'partial/paginator.phtml',
            array('route' => 'listPosts')); ?>
</div>