<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="page-header">
          <h1>Example page header <small>Subtext for header</small></h1>
        </div>
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button">Toggle nav</button>
            </p>
            <div class="row">
                <?php if (count($this->tags)): ?>
                    <?php foreach ($this->tags as $tag): ?>
                        <div class="col-xs-6 col-lg-4">
                            <div class="div-1">
                            <h3><a href="<?php echo $this->url('detailTag',
                                array('action' => 'detailTag', 'id' => $tag->getId())); ?>">
                                <?php echo $this->escapeHtml($tag->getTitle()); ?></a></h3>

                            <p>
                               Tag id: <?php echo $this->escapeHtml($tag->getId()); ?>
                            </p>
                            <p>
                               Tag weight: <?php echo $this->escapeHtml($tag->getWeight()); ?>
                            </p>
                            <p>
                               Просмотреть статьи с этим тегом: <a href="<?php echo $this->url('listPostsByTag',
                                array('action' => 'listPostsByTag', 'id' => $tag->getId())); ?>">
                                тыц</a>
                            </p>
                            </div>
                        </div><!--/.col-xs-6.col-lg-4-->
                    <?php endforeach; ?>
                <?php endif; ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class="list-group">
                <a class="list-group-item" href="<?php echo $this->url('listPosts',
                    array('action' => 'listPosts')); ?>">Articles</a>
                <a class="list-group-item" href="<?php echo $this->url('listCategories',
                    array('action' => 'listCategories')); ?>">Categories</a>
                <a class="list-group-item" href="#">Archives</a>
                <a class="list-group-item" href="<?php echo $this->url('listTags',
                    array('action' => 'listTags')); ?>">Tags</a>
            </div>
            <?php echo $this->partial('partial/contentManagerPanel.phtml'); ?>
        </div><!--/.sidebar-offcanvas-->
    </div><!--/row-->

    <?php echo $this->paginationControl($this->tags,
            'Sliding',
            'partial/paginator.phtml',
            array('route' => 'listTags')); ?>
</div>