<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="page-header">
            <h1><?php echo $this->translate('Archives'); ?></h1>
        </div>
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button">Toggle nav</button>
            </p>
            <?php $countColumns = 3;
            $countArchives = $this->archives->getCurrentItemCount();
            $iterator = $this->archives->getIterator();
            if ($countArchives):
                for ($i = 0; $i < $countArchives; $i = $i + $countColumns ): ?>
                    <div class="row">
                        <?php for ($j = 0; $j < $countColumns; $j++):
                            if ($iterator->valid()): ?>
                                <div class="col-xs-12 col-md-4">
                                    <div class="div-1">
                                        <?php $archive = $iterator->current();
                                        //\Zend\Debug\Debug::dump($archive);
                                        $iterator->next(); ?>
                                        <h1>
                                            <a href="<?php echo $this->url('listArchivesPosts',
                                                array('action' => 'listArchivesPosts', 'page' => '1', 'year' => $archive->year, 'month' => $archive->month, 'day' => $archive->day)); ?>">
                                                <?php echo $this->escapeHtml($archive->year . '-'
                                                    . $archive->month . '-'
                                                    . $archive->day
                                                    ); ?>
                                            </a>
                                        </h1>
                                    </div>
                                    <p>
                                        <?php echo $this->translate('Total articles'); ?>: <?php echo $this->escapeHtml($archive->total); ?>
                                    </p>
                                </div>
                            <?php endif;
                        endfor; ?>
                    </div>
                <?php endfor;
            endif; ?>
        </div>
        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class="list-group">
                <a class="list-group-item" href="<?php echo $this->url('listCategories',
                    array('action' => 'listCategories')); ?>"><?php echo $this->translate('Categories') ?></a>
                <a class="list-group-item" href="<?php echo $this->url('listTags',
                    array('action' => 'listTags')); ?>"><?php echo $this->translate('Tags') ?></a>
            </div>
        </div>
    </div>
    <?php echo $this->paginationControl($this->archives,
        'Sliding',
        'partial/paginator.phtml',
        array('route' => $this->route)); ?>
</div>