<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button"><?php echo $this->translate('Toggle nav') ?></button>
            </p>
            <div class="jumbotron">
                <h1><?php echo $this->escapeHtml($this->greeting['greeting']['caption']); ?></h1>
                <p><?php echo $this->escapeHtml($this->greeting['greeting']['message']); ?>
                <?php if ($this->isGranted('edit.greeting')): ?>
                <a role="button" class="btn btn-default pull-right" href="<?php echo $this->url('editGreeting',['action' => 'editGreeting']); ?>">Edit</a>
                <?php endif; ?>
                </p>
            </div>
            <?php $countColumns = 3;
            $countPosts = $this->posts->getCurrentItemCount();
            $iterator = $this->posts->getIterator();
            if ($countPosts):
                for ($i = 0; $i < $countPosts; $i = $i + $countColumns ): ?>
                    <div class="row">
                        <?php for ($j = 0; $j < $countColumns; $j++):
                            if ($iterator->valid()): ?>
                                <div class="col-xs-12 col-md-4">
                                    <div class="div-1">
                                        <?php $post = $iterator->current();
                                        $iterator->next(); ?>
                                        <h1><a href="<?php echo $this->url('detailPost',
                                            array('action' => 'detailPost', 'id' => $post->getId())); ?>">
                                            <?php echo $this->escapeHtml($post->getTitle()); ?></a>
                                        </h1>
                                        <p>
                                            <?php echo $this->htmlPurifier($post->getSummary()); ?>
                                        </p>
                                    </div>
                                    <p><a role="button" href="<?php echo $this->url('detailPost',
                                        array('action' => 'detailPost', 'id' => $post->getId())); ?>" class="btn btn-default"><?php echo $this->translate('View details') ?></a>
                                    </p>
                                </div>
                            <?php endif;
                        endfor; ?>
                    </div>
                <?php endfor;
            endif; ?>
        </div>
        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class="list-group">
                <a class="list-group-item" href="<?php echo $this->url('listCategories',
                    array('action' => 'listCategories')); ?>"><?php echo $this->translate('Categories') ?></a>
                <a class="list-group-item" href="<?php echo $this->url('listTags',
                    array('action' => 'listTags')); ?>"><?php echo $this->translate('Tags') ?></a>
            </div>
            <div class="sidebar-module">
                <?php echo $this->partial('partial/listArchivePanel.phtml'); ?>
            </div>
            <?php //echo $this->partial('partial/contentManagerPanel.phtml'); ?>
        </div>
    </div>

    <?php echo $this->paginationControl($this->posts,
            'Sliding',
            'partial/paginator.phtml',
            array('route' => $route)); ?>
</div>


