<div class="container">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="page-header">
          <h1>Example page header <small>Subtext for header</small></h1>
        </div>
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button">Toggle nav</button>
            </p>
            <div class="row">
                <?php if (count($this->categories)): ?>
                    <?php foreach ($this->categories as $category): ?>
                        <div class="col-xs-6 col-lg-4">
                            <div class="div-1">
                            <h3><a href="<?php echo $this->url('detailCategory',
                                array('action' => 'detailCategory', 'id' => $category->getId())); ?>">
                                <?php echo $this->escapeHtml($category->getTitle()); ?></a></h3>

                            <p>
                               Category id: <?php echo $this->escapeHtml($category->getId()); ?>
                            </p>
                            <p>
                               Category description: <?php echo $this->escapeHtml($category->getDescription()); ?>
                            </p>
                            <p>
                               Просмотреть статьи этой категории: <a href="<?php echo $this->url('listPostsByCategory',
                                array('action' => 'listPostsByCategory', 'id' => $category->getId())); ?>">
                                тыц</a>
                            </p>
                            </div>
                        </div><!--/.col-xs-6.col-lg-4-->
                    <?php endforeach; ?>
                <?php endif; ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class="list-group">
                <a class="list-group-item" href="<?php echo $this->url('listPosts',
                    array('action' => 'listPosts')); ?>">Articles</a>
                <a class="list-group-item" href="<?php echo $this->url('listCategories',
                    array('action' => 'listCategories')); ?>">Categories</a>
                <a class="list-group-item" href="#">Archives</a>
                <a class="list-group-item" href="<?php echo $this->url('listTags',
                    array('action' => 'listTags')); ?>">Tags</a>
            </div>
            <?php echo $this->partial('partial/contentManagerPanel.phtml'); ?>
        </div><!--/.sidebar-offcanvas-->
    </div><!--/row-->

    <?php echo $this->paginationControl($this->categories,
            'Sliding',
            'partial/paginator.phtml',
            array('route' => 'listCategories')); ?>
</div>