<div class="container">
    <div class="page-header">
        <h1><?php echo $this->translate('Client decription'); ?></h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div>
                <h2><?php echo $this->escapeHtml($client->getClientId()); ?></h2>
                <p>
                    <?php echo $this->translate('Grant types'); ?>: <?php echo $this->escapeHtml($client->getGrantTypes()); ?>
                </p>
                <p>
                    <?php echo $this->translate('Scope'); ?>: <?php echo $this->escapeHtml($client->getScope()); ?>
                </p>
                <p>
                    <?php echo $this->translate('User ID'); ?>: <?php echo $this->escapeHtml($client->getUserId()); ?>
                </p>
                <p>
                    <a href="<?php echo $this->url('revokeToken', array('action' => 'revokeToken', 'client_id' => $client->getClientId())); ?>"><?php echo $this->translate('Revoke token'); ?></a>
                </p>
               <p>
                    <a href="<?php echo $this->url('deleteClient', array('action' => 'deleteClient', 'client_id' => $client->getClientId())); ?>"><?php echo $this->translate('Delete client'); ?></a>
                </p>
            </div>
        </div>
    </div>
</div>