<div class="row row-offcanvas row-offcanvas-right">
    <div class="page-header">
      <h1>Example page header <small>Subtext for header</small></h1>
    </div>
    <div class="col-xs-12 col-sm-9">
        <p class="pull-right visible-xs">
            <button data-toggle="offcanvas" class="btn btn-primary btn-xs" type="button">Toggle nav</button>
        </p>
        <div class="row">
            <?php if (count($this->clients)): ?>
                <?php foreach ($this->clients as $client): ?>
                    <div class="col-xs-6 col-lg-4">
                        <div class="div-1">
                        <h3><a href="<?php echo $this->url('detailClient',
                            array('action' => 'detailClient', 'client_id' => $client['client_id'])); ?>">
                            <?php echo $this->escapeHtml($client['client_id']); ?></a></h3>

<!--                        <p>
                           Tag id: <?php //echo $this->escapeHtml($tag->getId()); ?>
                        </p>-->

                        </div>
                    </div><!--/.col-xs-6.col-lg-4-->
                <?php endforeach; ?>
            <?php endif; ?>
        </div><!--/row-->
    </div><!--/.col-xs-12.col-sm-9-->

    <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
        <div class="list-group">
            <a class="list-group-item" href="<?php echo $this->url('listPosts',
                array('action' => 'listPosts')); ?>">Articles</a>
            <a class="list-group-item" href="<?php echo $this->url('listCategories',
                array('action' => 'listCategories')); ?>">Categories</a>
            <a class="list-group-item" href="#">Archives</a>
            <a class="list-group-item" href="<?php echo $this->url('listTags',
                array('action' => 'listTags')); ?>">Tags</a>
        </div>
        <?php echo $this->partial('partial/contentManagerPanel.phtml'); ?>
    </div><!--/.sidebar-offcanvas-->
</div><!--/row-->

<?php echo $this->paginationControl($this->clients,
        'Sliding',
        'partial/paginator.phtml',
        array('route' => 'listClients')); ?>