<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner dialog">
                <h2 class="form-signin-heading">
                    <?php echo $this->translate('Are you sure that you want to revoke token of client'); ?>?
                </h2>
                <p>
                    <?php echo $this->translate('Client'); ?>
                    "<?php echo $this->escapeHtml($this->client->getClientID()); ?>"
                </p>
                <form action="<?php echo $this->url('revokeToken', array(), true) ?>" method="post">
                    <input type="submit" class='btn btn-default' name="delete_confirmation" value="<?php echo $this->translate('Yes'); ?>">
                    <input type="submit" class='btn btn-default' name="delete_confirmation" value="<?php echo $this->translate('No'); ?>">
                </form>
            </div>
        </div>
    </div>
</div>