<?php if ($this->error): ?>
    <div class="container">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
            <?php
                echo $this->translate("There were one or more issues. Please correct them as indicated below.");
            ?>
            <strong>
                <?php
                    if (is_string($this->error)) {
                        echo $this->escapeHtml($this->translate($this->error)) . "!";
                    }
                    echo $this->formElementErrors($form->get('post')->get('title'));
                    echo $this->formElementErrors($form->get('post')->get('text'));
                    echo $this->formElementErrors($form->get('post')->get('summary'));
                    echo $this->formElementErrors($form->get('post')->get('category')->get('id'));
                ?>
            </strong>
        </div>
    </div>
<?php endif; ?>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <div class="page-header">
                <h1>Hello, world!</h1>
            </div>
                <?php $form = $this->form;
                $form->setAttribute('action', $this->url('addPost', array(), true));
                $form->prepare();
                echo $this->form()->openTag($form);
                $post = $form->get('post'); ?>
                <div class="form-group">
                    <?php echo $this->formRow($post->get('id')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('post')->get('title')->getMessages()) ? '' : 'has-error'; ?>">
                   <?php echo $this->formLabel($form->get('post')->get('title'));
                    echo $this->formElement($form->get('post')->get('title'));
                     ?>
                </div>
                <div class="form-group <?php echo empty($form->get('post')->get('text')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('post')->get('text'));
                    echo $this->formElement($form->get('post')->get('text'));
                    //echo $this->formRow($post->get('text')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('post')->get('summary')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('post')->get('summary'));
                    echo $this->formElement($form->get('post')->get('summary')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('post')->get('category')->get('id')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php $category = $post->get('category');
                    echo $this->formLabel($form->get('post')->get('category')->get('id'));
                    echo $this->formElement($form->get('post')->get('category')->get('id')); ?>
                </div>
                <?php echo $this->formCollection($post->get('tags'));
                //echo $this->formLabel($form->get('post')->get('tags')->get(0)->get('id'));
                //echo $this->formElement($form->get('post')->get('tags')->get(0)->get('id'));?>
                <button onclick="return add_category()" class="btn btn-default"><?php echo $this->translate('Add tag') ?></button>
                <div class="checkbox">
                    <label>
                        <?php echo $this->formElement($form->get('post')->get('isPublished'));
                        echo $this->translate('Publish'); ?>
                    </label>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <script>
                    function add_category() {
                        var currentCount = $('form > fieldset > fieldset').length;
                        var template = $('form > fieldset > span').data('template');
                        template = template.replace(/__index__/g, currentCount);
                        $('form > fieldset').append(template);

                        return false;
                    }
                </script>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>


