<?php if ($this->error) : ?>
    <div class="container">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
            <p>
                <?php
                    echo $this->translate("There were one or more issues. Please correct them as indicated below.");
                ?>
            </p>
            <p>
                <strong>
                    <?php
                        if (is_string($this->error)) {
                            echo $this->escapeHtml($this->translate($this->error)) . "!";
                        }
                        echo $this->formElementErrors($form->get('title'));
                        echo $this->formElementErrors($form->get('text'));
                    ?>
                </strong>
            </p>
        </div>
    </div>
<?php endif; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('addPost', array(), true));
$form->prepare();

//$form->get('submit')->setValue('Add Post');

echo $this->form()->openTag($form);

$post = $form->get('post');
echo $this->formRow($post->get('id'));
echo $this->formRow($post->get('title'));
echo $this->formRow($post->get('text'));
echo $this->formRow($post->get('summary'));

$category = $post->get('category');
echo $this->formRow($category->get('id'));
//echo $this->formRow($category->get('title'));

echo $this->formRow($post->get('isPublished'));

echo $this->formCollection($post->get('tags'));

echo $this->formElement($form->get('submit'));

//echo $this->formCollection($form);
?>

<button onclick="return add_category()" class="btn btn-default"><?php echo $this->translate('Add tag') ?></button>
<script>
    function add_category() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').data('template');
        template = template.replace(/__index__/g, currentCount);
        $('form > fieldset').append(template);

        return false;
    }
</script>

<?php
echo $this->form()->closeTag();



