<div class="list-group">

        <h4>Manage content</h4>
            <a class="list-group-item" href="<?php echo $this->url('addPost'); ?>">Add article</a>
            <a class="list-group-item" href="<?php echo $this->url('addCategory'); ?>">Add category</a>
            <a class="list-group-item" href="<?php echo $this->url('addTag'); ?>">Add tag</a>
        <?php if (isset($post) && $post instanceof MxmBlog\Model\Post): ?>
            <a class="list-group-item" href="<?php echo $this->url('editPost', array('action' => 'editPost', 'id' => $post->getId())); ?>">Edit article</a>
            <a class="list-group-item" href="<?php echo $this->url('deletePost', array('action' => 'deletePost', 'id' => $post->getId())); ?>">Delete article</a>
        <?php endif; ?>
        <?php if (isset($category) && $category instanceof MxmBlog\Model\Category): ?>
            <a class="list-group-item" href="<?php echo $this->url('editCategory', array('action' => 'editCategory', 'id' => $category->getId())); ?>">Edit category</a>
            <a class="list-group-item" href="<?php echo $this->url('deleteCategory', array('action' => 'deleteCategory', 'id' => $category->getId())); ?>">Delete category</a>
        <?php endif; ?>
        <?php if (isset($tag) && $tag instanceof MxmBlog\Model\Tag): ?>
            <a class="list-group-item" href="<?php echo $this->url('editTag', array('action' => 'editTag', 'id' => $tag->getId())); ?>">Edit tag</a>
            <a class="list-group-item" href="<?php echo $this->url('deleteTag', array('action' => 'deleteTag', 'id' => $tag->getId())); ?>">Delete tag</a>
        <?php endif; ?>

</div>