<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->first), FALSE, TRUE); ?>">
    <?php echo $this->translate('First'); ?>
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('First'); ?></span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->previous), FALSE, TRUE); ?>">
    &lt; <?php echo $this->translate('Previous'); ?>
  </a> |
<?php else: ?>
  <span class="disabled">&lt; <?php echo $this->translate('Previous'); ?></span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url($this->route, array('page' => $page), FALSE, TRUE); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->next), FALSE, TRUE); ?>">
    <?php echo $this->translate('Next'); ?> &gt;
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('Next'); ?> &gt;</span> |
<?php endif; ?>

  <!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->last), FALSE, TRUE); ?>">
    <?php echo $this->translate('Last'); ?>
  </a>
<?php else: ?>
  <span class="disabled"><?php echo $this->translate('Last'); ?></span>
<?php endif; ?>

</div>
<?php endif; ?>

