<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <?php echo $this->navigation('Zend\Navigation\adminSidebar')->menu()->setUlClass("nav nav-sidebar"); ?>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header"><?php echo $this->translate('Dashboard'); ?></h1>
            <h2 class="sub-header"><?php echo $this->translate('General information'); ?></h2>
            <div class="row placeholders">
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Total users'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($allUsers); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Admins'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($admins); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Moderators'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($moderators); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Authors'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($authors); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Users'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($users); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Files'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($files); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Clients'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($clients); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Posts'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($posts); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Categories'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($categories); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Tags'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($tags); ?></span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="100" height="100" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4><?php echo $this->translate('Logs'); ?></h4>
                    <span class="text-muted"><?php echo $this->escapeHtml($logs); ?></span>
                </div>
          </div>
        </div>
    </div>
</div>