<?php if ($this->error): ?>
    <div class="container">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
            <?php
                echo $this->translate("There were one or more issues. Please correct them as indicated below.");
            ?>
            <strong>
                <?php
                    if (is_string($this->error)) {
                        echo $this->escapeHtml($this->translate($this->error)) . "!";
                    }
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('username'));
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('email'));
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('password'));
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('confirmPassword'));
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('timebelt')->get('timezoneId'));
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('localeId'));
                    echo $this->formElementErrors($this->form->get('userFieldset')->get('captcha'));
                ?>
            </strong>
        </div>
    </div>
<?php endif; ?>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <div class="page-header">
                    <h1><?php echo $this->translate('Register, please') ?></h1>
                </div>
                <?php $form = $this->form;
                $form->setAttribute('action', $this->url('addUser', array(), true));
                $form->prepare();
                echo $this->form()->openTag($form);
                $userFieldset = $form->get('userFieldset'); ?>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('username')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('username'));
                    echo $this->formElement($form->get('userFieldset')->get('username')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('email')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('email'));
                    echo $this->formElement($form->get('userFieldset')->get('email')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('password')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('password'));
                    echo $this->formElement($form->get('userFieldset')->get('password')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('confirmPassword')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('confirmPassword'));
                    echo $this->formElement($form->get('userFieldset')->get('confirmPassword')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('timebelt')->get('timezoneId')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('timebelt')->get('timezoneId'));
                    echo $this->formElement($form->get('userFieldset')->get('timebelt')->get('timezoneId')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('localeId')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('localeId'));
                    echo $this->formElement($form->get('userFieldset')->get('localeId')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('userFieldset')->get('captcha')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('userFieldset')->get('captcha'));
                    echo $this->formElement($form->get('userFieldset')->get('captcha')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>