

<?php if ($this->error) : ?>
<p class="error">
    There were one or more issues with your submission. Please correct them as
    indicated below.
</p>
<p>
    <?php echo $this->escapeHtml($this->error); ?>
</p>
<?php endif; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('editUser', array(), true));
$form->prepare();

$form->get('submit')->setValue('Edit User');

echo $this->form()->openTag($form);

$user = $form->get('user');
//echo $this->formRow($user->get('id'));
echo $this->formElement($form->get('editUser_csrf'));
echo $this->formRow($user->get('username'));

if ($user->has('role')) {
    echo $this->formRow($user->get('role'));
}

echo $this->formRow($user->get('localeId'));

$timezone = $user->get('timebelt');
echo $this->formRow($timezone->get('timezoneId'));

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>
