<?php if ($this->error): ?>
    <div class="container">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
            <?php
                echo $this->translate("There were one or more issues. Please correct them as indicated below.");
            ?>
            <strong>
                <?php
                    if (is_string($this->error)) {
                        echo $this->escapeHtml($this->translate($this->error)) . "!";
                    }
                    echo $this->formElementErrors($this->form->get('password'));
                    echo $this->formElementErrors($this->form->get('confirmPassword'));
                    echo $this->formElementErrors($this->form->get('setPassword_captcha'));
                ?>
            </strong>
        </div>
    </div>
<?php endif; ?>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <div class="page-header">
                    <h1><?php echo $this->translate('Set new password, please') ?></h1>
                </div>
                <?php $form = $this->form;
                $form->setAttribute('action', $this->url('setPassword', array(), true));
                $form->prepare();
                echo $this->form()->openTag($form); ?>
                <div class="form-group">
                   <?php echo $this->formElement($form->get('token')); ?>
                </div>
                <div class="form-group <?php echo empty($form->get('password')->getMessages()) ? '' : 'has-error'; ?>">
                   <?php echo $this->formLabel($form->get('password'));
                    echo $this->formElement($form->get('password'));
                    ?>
                </div>
                <div class="form-group <?php echo empty($form->get('confirmPassword')->getMessages()) ? '' : 'has-error'; ?>">
                   <?php echo $this->formLabel($form->get('confirmPassword'));
                    echo $this->formElement($form->get('confirmPassword'));
                    ?>
                </div>
                <div class="form-group <?php echo empty($form->get('setPassword_captcha')->getMessages()) ? '' : 'has-error'; ?>">
                   <?php echo $this->formLabel($form->get('setPassword_captcha'));
                    echo $this->formElement($form->get('setPassword_captcha'));
                    ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('setPassword_csrf')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>