<?php

namespace MxmBlog\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-04 at 13:41:33.
 */
class ListControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ListController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ListController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers MxmBlog\Controller\ListController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listPostsAction
     * @todo   Implement testListPostsAction().
     */
    public function testListPostsAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listPostsByCategoryAction
     * @todo   Implement testListPostsByCategoryAction().
     */
    public function testListPostsByCategoryAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listPostsByTagAction
     * @todo   Implement testListPostsByTagAction().
     */
    public function testListPostsByTagAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listPostsByPublishedAction
     * @todo   Implement testListPostsByPublishedAction().
     */
    public function testListPostsByPublishedAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listArchivesPostsAction
     * @todo   Implement testListArchivesPostsAction().
     */
    public function testListArchivesPostsAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listArchivesAction
     * @todo   Implement testListArchivesAction().
     */
    public function testListArchivesAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::detailPostAction
     * @todo   Implement testDetailPostAction().
     */
    public function testDetailPostAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listCategoriesAction
     * @todo   Implement testListCategoriesAction().
     */
    public function testListCategoriesAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::detailCategoryAction
     * @todo   Implement testDetailCategoryAction().
     */
    public function testDetailCategoryAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::listTagsAction
     * @todo   Implement testListTagsAction().
     */
    public function testListTagsAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmBlog\Controller\ListController::detailTagAction
     * @todo   Implement testDetailTagAction().
     */
    public function testDetailTagAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
