<?php

//namespace MxmUser\Controller;

namespace MxmUserTest\Controller;

use MxmUser\Controller\ListController;
use Zend\Stdlib\ArrayUtils;
use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-04 at 13:39:53.
 */
class ListControllerTest extends AbstractHttpControllerTestCase //\PHPUnit_Framework_TestCase
{

    /**
     * @var ListController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // The module configuration should still be applicable for tests.
        // You can override configuration here with test case specific values,
        // such as sample view templates, path stacks, module_listener_options,
        // etc.
        $configOverrides = [];

        $this->setApplicationConfig(ArrayUtils::merge(
            // Grabbing the full application configuration:
            include __DIR__ . '/../../../../../../config/application.config.php',
            $configOverrides
        ));
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers MxmUser\Controller\ListController::listUsersAction
     * @todo   Implement testListUsersAction().
     */
    public function testListUsersAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MxmUser\Controller\ListController::detailUserAction
     * @todo   Implement testDetailUserAction().
     */
    public function testDetailUserAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
