<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Site name')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/cover.css'))
                        ->prependStylesheet($this->basePath('css/offcanvas.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=PT+Mono') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/ajax.js'))
            ->prependFile($this->basePath('js/386.js'))
            ->prependFile($this->basePath('js/offcanvas.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            //->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php echo $this->partial('partial/fixedTopNavbar.phtml'); ?>
        <?php echo $this->content; ?>
        <div class="container">
            <hr>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> Site name. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
