<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/cover.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()

            ->prependFile($this->basePath('js/386.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            //->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                        <span class="sr-only"><?php echo $this->translate('Toggle navigation') ?></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?php echo $this->url('home'); ?>" class="navbar-brand"><?php echo $this->translate('Home') ?></a>
                </div>
                <div class="navbar-collapse collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('changeLanguage',['action' => 'changeLanguage'],['query' => ['lang' => 'Ru',],]); ?>">Рус</a></li>
                        <li><a href="<?php echo $this->url('changeLanguage',['action' => 'changeLanguage'],['query' => ['lang' => 'En',],]); ?>">En</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <?php $user = $this->identity();
                                if ($user) {
                                    echo $this->translate('Logged in');
                                } else {
                                    echo $this->translate('Not logged in');
                                } ?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">
                                    <?php if ($user) {
                                        echo $this->translate('Hello') . ', ' . $this->escapeHtml($user->getUserName());
                                    } else {
                                        echo $this->translate('Not logged in');
                                    } ?>
                                </li>
                                <li class="divider" role="separator"></li>
                                <?php if ($user) { ?>
                                    <li>
                                        <a href="<?php echo $this->url('detailUser', ['action' => 'detailUser', 'id' => $user->getId()]); ?>"><?php echo $this->translate('Profile') ?></a>
                                    </li>
                                <?php } ?>
                                <li>
                                    <a href="<?php if ($user) {
                                            echo $this->url('logoutUser');
                                        } else {
                                            echo $this->url('loginUser');
                                        } ?>">
                                        <?php if ($user) {
                                            echo $this->translate('Logout');
                                        } else {
                                            echo $this->translate('Login');
                                        } ?>
                                    </a>
                                </li>
                                <?php if (!$user) { ?>
                                    <li>
                                        <a href="<?php echo $this->url('addUser', ['action' => 'addUser']); ?>"><?php echo $this->translate('Register') ?></a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url('resetPassword', ['action' => 'resetPassword']); ?>"><?php echo $this->translate('Reset password') ?></a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

            <?php echo $this->content; ?>

        <div class="container">
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
