<?php
    echo $this->headLink()->prependStylesheet($this->basePath('css/life.css'));
    $this->headScript()->setAllowArbitraryAttributes(true);
    echo $this->headScript()->prependFile($this->basePath('js/life/life.js'));
?>
<form id = "myform">
    <b>Probability</b>
    <select size = "1" id = "probability">
        <option value = "0.1">0.10</option>
        <option value = "0.2">0.20</option>
        <option value = "0.3">0.30</option>
        <option value = "0.5">0.50</option>
        <option value = "0.75">0.750</option>
    </select>
    <b>Time</b>
    <select size = "1" id = "life_speed">
        <option value = "50">0.05</option>
        <option value = "100">0.10</option>
        <option value = "200">0.20</option>
        <option value = "300">0.30</option>
        <option value = "500">0.50</option>
        <option value = "750">0.750</option>
    </select>
    <input type = "button" id = "configuration" value = "New config">
    <input type = "button" id = "start" style = "width: 120px;">
    <input type = "button" id = "erase" style = "width: 120px;" value = "Erase">
</form>
<canvas id = "mycanvas" style = "border: ridge;"></canvas>
<br>