<?php if ($this->error): ?>
    <div class="container">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
            </button>
            <?php
                echo $this->translate("There were one or more issues. Please correct them as indicated below.");
            ?>
            <strong>
                <?php
                    if (is_string($this->error)) {
                        echo $this->escapeHtml($this->translate($this->error)) . "!";
                    }
                    echo $this->formElementErrors($form->get('game')->get('title'));
                ?>
            </strong>
        </div>
    </div>
<?php endif; ?>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <div class="page-header">
                <h1><?php echo $this->translate('Add game description, please.') ?></h1>
            </div>
                <?php $form = $this->form;
                $form->setAttribute('action', $this->url('addGame', array(), true));
                $form->prepare();
                echo $this->form()->openTag($form); ?>
                <div class="form-group <?php echo empty($form->get('title')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('title'));
                    echo $this->formElement($form->get('title'));
                    ?>
                </div>
                <div class="form-group <?php echo empty($form->get('description')->getMessages()) ? '' : 'has-error'; ?>">
                    <?php echo $this->formLabel($form->get('description'));
                    echo $this->formElement($form->get('description'));
                    ?>
                </div>
                <div class="checkbox">
                    <label>
                        <?php echo $this->formElement($form->get('isPublished'));
                        echo $this->translate('Publish'); ?>
                    </label>
                </div>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>